### ISSUE TITLE
ts.JsxEmit.React is undefined within options.mjs

### ISSUE THREAD

**Issue by danvim** [joshwooding/vite-plugin-react-docgen-typescript#22]
I believe the built `dist/chunks/options.mjs` code might have some issues, namely the TypeScript import. You might want to check all mjs files.

From debugging:

```ts
import * as ts from 'typescript';

ts.JsxEmit // undefined
ts.default.JsxEmit // object
```

<img width="667" alt="image" src="https://user-images.githubusercontent.com/5255292/234649710-19d10d20-97f0-4402-80de-128b3238a8e6.png">

---

**test.mjs**

```js
import * as ts from 'typescript'

console.log('ts.JsxEmit', ts.JsxEmit)
console.log('ts.default.JsxEmit', ts.default.JsxEmit)
```

**Run results**

```shell
$ node test.mjs
ts.JsxEmit undefined
ts.default.JsxEmit {
  '0': 'None',
  '1': 'Preserve',
  '2': 'React',
  '3': 'ReactNative',
  '4': 'ReactJSX',
  '5': 'ReactJSXDev',
  None: 0,
  Preserve: 1,
  React: 2,
  ReactNative: 3,
  ReactJSX: 4,
  ReactJSXDev: 5
}
```

**Comment by rogerluiz** [comment]
im with the same error, any workaround?

**Comment by joshwooding** [comment]
What version of typescript are you using?

**Comment by danvim** [comment]
version 5.0.4

**Comment by danvim** [comment]
> im with the same error, any workaround?

@rogerluiz The fix should be `import ts from 'typescript'` instead of the asterisk import. But only monkey patching the lib code would work.

**Comment by andrewmozolev** [comment]
I have just got the same error with typescript 5.2.2. Do you have any suggestions on how to work around the problem?
